// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['facade']['Service']['GetConfig']();
}

export function Initialize() {
  return window['go']['facade']['Service']['Initialize']();
}

export function SetContainer(arg1) {
  return window['go']['facade']['Service']['SetContainer'](arg1);
}

export function UpdateConfig() {
  return window['go']['facade']['Service']['UpdateConfig']();
}
