// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {iocdi} from '../models';
import {context} from '../models';

export function GetConfig():Promise<types.AppConfig>;

export function Initialize():Promise<void>;

export function SetContainer(arg1:iocdi.Container):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;

export function UpdateConfig():Promise<void>;
