package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestValidateCatalogRejectsAmbiguousCanonicalTopic(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "docs/one.md")
	writeTestFile(t, root, "docs/two.md")

	c := catalog{Version: 1, Documents: []document{
		testDocument("one", "docs/one.md", "canonical", "ft8"),
		testDocument("two", "docs/two.md", "canonical", "ft8"),
	}}

	err := validateCatalog(root, c)
	if err == nil {
		t.Fatal("validateCatalog accepted two canonical owners for topic ft8")
	}
	for _, want := range []string{"ft8", "one", "two"} {
		if !strings.Contains(err.Error(), want) {
			t.Fatalf("ambiguity error %q does not identify %q", err, want)
		}
	}
}

func TestValidateCatalogRejectsMissingDocumentPath(t *testing.T) {
	root := t.TempDir()
	c := catalog{Version: 1, Documents: []document{
		testDocument("missing", "docs/missing.md", "canonical", "api"),
	}}

	err := validateCatalog(root, c)
	if err == nil {
		t.Fatal("validateCatalog accepted a document path that does not exist")
	}
	if !strings.Contains(err.Error(), "docs/missing.md") {
		t.Fatalf("missing-path error %q does not name the missing path", err)
	}
}

func TestValidateCatalogRejectsMissingScopePath(t *testing.T) {
	root := t.TempDir()
	writeTestFile(t, root, "docs/one.md")
	writeTestFile(t, root, "frontend/app/src/not-a-directory")

	tests := []struct {
		name  string
		scope string
	}{
		{name: "exact", scope: "frontend/app/src/missing.ts"},
		{name: "wildcard base", scope: "frontend/app/src/missing/**"},
		{name: "wildcard base is file", scope: "frontend/app/src/not-a-directory/**"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			doc := testDocument("one", "docs/one.md", "canonical", "api")
			doc.Scopes = []string{tt.scope}
			c := catalog{Version: 1, Documents: []document{doc}}

			err := validateCatalog(root, c)
			if err == nil {
				t.Fatalf("validateCatalog accepted missing scope %q", tt.scope)
			}
			for _, want := range []string{"one", tt.scope} {
				if !strings.Contains(err.Error(), want) {
					t.Fatalf("missing-scope error %q does not identify %q", err, want)
				}
			}
		})
	}
}

func TestFindDocumentsResolvesTopicAndCodePath(t *testing.T) {
	c := catalog{Version: 1, Documents: []document{
		{
			ID:        "ft8-kernel",
			Path:      "internal/ft8/AGENTS.md",
			Class:     "kernel",
			Audiences: []string{"agent"},
			Topics:    []string{"ft8-safety"},
			Scopes:    []string{"internal/ft8/**"},
			Summary:   "Local FT8 safety rules.",
		},
		{
			ID:        "ft8-guide",
			Path:      "docs/ft8.md",
			Class:     "canonical",
			Audiences: []string{"operator", "contributor", "agent"},
			Topics:    []string{"ft8"},
			Scopes:    []string{"internal/ft8/**", "frontend/app/src/lib/ft8/**"},
			Summary:   "Current FT8 behavior and subsystem reference.",
		},
	}}

	byTopic := findDocuments(c, "ft8")
	if len(byTopic) != 2 {
		t.Fatalf("findDocuments(ft8) returned %d documents, want both kernel and canonical guide", len(byTopic))
	}
	if byTopic[0].ID != "ft8-guide" {
		t.Fatalf("findDocuments(ft8) ranked %q first, want canonical ft8-guide", byTopic[0].ID)
	}

	byPath := findDocuments(c, "internal/ft8/sequencer.go")
	if len(byPath) != 2 {
		t.Fatalf("findDocuments(code path) returned %d documents, want scoped kernel and canonical guide", len(byPath))
	}
}

func TestRenderREADMEExposesAudienceClassTopicAndRecordRoutes(t *testing.T) {
	c := catalog{Version: 1, Documents: []document{
		{
			ID:        "root-kernel",
			Path:      "AGENTS.md",
			Class:     "kernel",
			Audiences: []string{"contributor", "agent"},
			Topics:    []string{"contributing"},
			Scopes:    []string{"repository"},
			Summary:   "Project rules and routing.",
		},
		{
			ID:        "ft8-guide",
			Path:      "docs/ft8.md",
			Class:     "canonical",
			Audiences: []string{"operator", "contributor", "agent"},
			Topics:    []string{"ft8"},
			Scopes:    []string{"internal/ft8/**"},
			Summary:   "Current FT8 behavior and subsystem reference.",
		},
		{
			ID:        "work-one",
			Path:      "docs/work/W-0001.md",
			Class:     "work-item",
			Audiences: []string{"contributor", "agent"},
			Topics:    []string{"active-work"},
			Scopes:    []string{"repository"},
			Summary:   "Selected work dossier.",
		},
	}}

	gotBytes, err := renderREADME(c)
	if err != nil {
		t.Fatalf("renderREADME: %v", err)
	}
	got := string(gotBytes)
	for _, want := range []string{
		"Code generated by `task docs:generate`",
		"## Browse by audience",
		"## Live documents by class",
		"### Work Items and Dossiers",
		"## Canonical topic routing",
		"## Records and history",
		"[root-kernel](../AGENTS.md)",
		"[ft8-guide](ft8.md)",
		"`task docs:find QUERY=internal/ft8`",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated README does not contain %q", want)
		}
	}
}

func TestRepositoryCatalogRoutesLiveFrontendScopes(t *testing.T) {
	repoRoot := filepath.Clean(filepath.Join("..", ".."))
	c, err := loadCatalog(filepath.Join(repoRoot, "docs", "catalog.json"))
	if err != nil {
		t.Fatalf("load repository catalog: %v", err)
	}

	tests := []struct {
		query string
		want  string
	}{
		{query: "frontend/app/src/lib/config/Settings.svelte", want: "reference.config"},
		{query: "frontend/app/src/lib/operate/Ft8Occupancy.svelte", want: "reference.ft8"},
	}
	for _, tt := range tests {
		t.Run(tt.want, func(t *testing.T) {
			got := findDocuments(c, tt.query)
			if !containsDocument(got, tt.want) {
				t.Fatalf("findDocuments(%q) omitted %q; got %v", tt.query, tt.want, documentIDs(got))
			}
		})
	}
}

func TestRepositoryCatalogIsValidAndREADMEIsCurrent(t *testing.T) {
	repoRoot := filepath.Clean(filepath.Join("..", ".."))
	catalogPath := filepath.Join(repoRoot, "docs", "catalog.json")

	c, err := loadCatalog(catalogPath)
	if err != nil {
		t.Fatalf("load repository catalog: %v", err)
	}
	if err := validateCatalog(repoRoot, c); err != nil {
		t.Fatalf("validate repository catalog: %v", err)
	}

	want, err := renderREADME(c)
	if err != nil {
		t.Fatalf("render repository README: %v", err)
	}
	readmePath := filepath.Join(repoRoot, "docs", "README.md")
	got, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatalf("read generated documentation map: %v", err)
	}
	if string(got) != string(want) {
		t.Fatal("docs/README.md is stale; run task docs:generate")
	}
}

func testDocument(id, path, class, topic string) document {
	return document{
		ID:        id,
		Path:      path,
		Class:     class,
		Audiences: []string{"contributor"},
		Topics:    []string{topic},
		Scopes:    []string{"repository"},
		Summary:   "Test document.",
	}
}

func containsDocument(documents []document, id string) bool {
	for _, doc := range documents {
		if doc.ID == id {
			return true
		}
	}
	return false
}

func documentIDs(documents []document) []string {
	ids := make([]string, len(documents))
	for index, doc := range documents {
		ids[index] = doc.ID
	}
	return ids
}

func writeTestFile(t *testing.T, root, name string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir test document: %v", err)
	}
	if err := os.WriteFile(path, []byte("# Test\n"), 0o644); err != nil {
		t.Fatalf("write test document: %v", err)
	}
}
