// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {iocdi} from '../models';
import {context} from '../models';

export function CatStatus():Promise<Record<string, string>>;

export function CurrentSessionQsoSlice():Promise<Array<types.Qso>>;

export function FetchCatStateValues():Promise<Record<string, Record<string, string>>>;

export function FetchUiConfig():Promise<types.UiConfig>;

export function FinaliseSetup(arg1:types.Logbook):Promise<void>;

export function ForwardSessionQsosByEmail(arg1:Array<types.Qso>,arg2:string):Promise<void>;

export function GetQsoById(arg1:number):Promise<types.Qso>;

export function HasDefaultLogbook():Promise<boolean>;

export function Initialize():Promise<void>;

export function IsContestDuplicate(arg1:string,arg2:string):Promise<boolean>;

export function LogQso(arg1:types.Qso):Promise<void>;

export function NewQso(arg1:string):Promise<types.Qso>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function Ready():Promise<void>;

export function SetContainer(arg1:iocdi.Container):Promise<void>;

export function Start(arg1:context.Context):Promise<void>;

export function StartDatabase(arg1:context.Context):Promise<void>;

export function Stop():Promise<void>;

export function StopDatabase():Promise<void>;

export function TotalQsosByLogbookId(arg1:number):Promise<number>;

export function UpdateQso(arg1:types.Qso):Promise<void>;
