// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CatStatus() {
  return window['go']['facade']['Service']['CatStatus']();
}

export function CurrentSessionQsoSlice() {
  return window['go']['facade']['Service']['CurrentSessionQsoSlice']();
}

export function FetchCatStateValues() {
  return window['go']['facade']['Service']['FetchCatStateValues']();
}

export function FetchUiConfig() {
  return window['go']['facade']['Service']['FetchUiConfig']();
}

export function FinaliseSetup(arg1) {
  return window['go']['facade']['Service']['FinaliseSetup'](arg1);
}

export function ForwardSessionQsosByEmail(arg1, arg2) {
  return window['go']['facade']['Service']['ForwardSessionQsosByEmail'](arg1, arg2);
}

export function GetQsoById(arg1) {
  return window['go']['facade']['Service']['GetQsoById'](arg1);
}

export function HasDefaultLogbook() {
  return window['go']['facade']['Service']['HasDefaultLogbook']();
}

export function Initialize() {
  return window['go']['facade']['Service']['Initialize']();
}

export function IsContestDuplicate(arg1, arg2) {
  return window['go']['facade']['Service']['IsContestDuplicate'](arg1, arg2);
}

export function LogQso(arg1) {
  return window['go']['facade']['Service']['LogQso'](arg1);
}

export function NewQso(arg1) {
  return window['go']['facade']['Service']['NewQso'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['facade']['Service']['OpenInBrowser'](arg1);
}

export function Ready() {
  return window['go']['facade']['Service']['Ready']();
}

export function SetContainer(arg1) {
  return window['go']['facade']['Service']['SetContainer'](arg1);
}

export function Start(arg1) {
  return window['go']['facade']['Service']['Start'](arg1);
}

export function StartDatabase(arg1) {
  return window['go']['facade']['Service']['StartDatabase'](arg1);
}

export function Stop() {
  return window['go']['facade']['Service']['Stop']();
}

export function StopDatabase() {
  return window['go']['facade']['Service']['StopDatabase']();
}

export function TotalQsosByLogbookId(arg1) {
  return window['go']['facade']['Service']['TotalQsosByLogbookId'](arg1);
}

export function UpdateQso(arg1) {
  return window['go']['facade']['Service']['UpdateQso'](arg1);
}
