package api

import (
	"encoding/json"
	stderrs "errors"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/ColonelBlimp/station-manager/internal/email"
	"github.com/ColonelBlimp/station-manager/internal/errors"
)

// SessionEmailRequest is the SPA's POST body. `to` is the recipient
// (typically the operator's QSL manager); `adif` is the full ADIF
// blob the SPA built from the in-tab session QSO list. `subject`
// and `filename` are optional; the daemon stamps reasonable defaults
// from the current UTC time when absent so the SPA doesn't need
// timezone-aware formatting code.
type SessionEmailRequest struct {
	To       string `json:"to"`
	Subject  string `json:"subject,omitempty"`
	ADIF     string `json:"adif"`
	Filename string `json:"filename,omitempty"`
}

// handleSessionEmail packages the SPA-supplied ADIF as an email
// attachment and dispatches via the daemon's mailer.
//
// POST /v1/session/email
//
// Status codes:
//
//	200  body: {"status":"sent"} on successful send.
//	400  validation: missing to / adif, malformed JSON, etc.
//	503  mailer disabled (smtp.host empty in config) — operator
//	     hasn't configured SMTP; SPA toasts "email not configured".
//	502  SMTP transport failure (DNS / TLS / auth / RCPT rejected)
//	     — wraps the underlying error so logs carry the cause.
//
// The body part is a one-line "ADIF for session ... attached."
// summary; future versions can let the operator type a free-text
// note from the panel before send.
func (s *Server) handleSessionEmail(w http.ResponseWriter, r *http.Request) {
	const op errors.Op = "api.handleSessionEmail"

	if !s.mailer.Enabled() {
		s.writeError(w, http.StatusServiceUnavailable, "mailer_disabled",
			"SMTP is not configured (smtp.host is empty)", op)
		return
	}

	var req SessionEmailRequest
	if err := json.NewDecoder(http.MaxBytesReader(w, r.Body, s.maxBodyBytes)).Decode(&req); err != nil {
		s.writeError(w, http.StatusBadRequest, "invalid_json",
			fmt.Sprintf("could not decode request body: %v", err), op)
		return
	}

	req.To = strings.TrimSpace(req.To)
	req.Subject = strings.TrimSpace(req.Subject)
	req.Filename = strings.TrimSpace(req.Filename)

	if req.To == "" {
		s.writeError(w, http.StatusBadRequest, "missing_required_field",
			"to is required", op)
		return
	}
	if req.ADIF == "" {
		s.writeError(w, http.StatusBadRequest, "missing_required_field",
			"adif is required", op)
		return
	}
	if !strings.Contains(req.To, "@") {
		s.writeError(w, http.StatusBadRequest, "invalid_field_value",
			"to must be an email address", op)
		return
	}

	// Daemon-side defaults for subject + filename. Operator-supplied
	// values pass through untouched. UTC stamp for reproducibility
	// across operators in different timezones.
	now := time.Now().UTC()
	if req.Subject == "" {
		req.Subject = fmt.Sprintf("Station Manager session ADIF — %s", now.Format("2006-01-02 15:04 UTC"))
	}
	if req.Filename == "" {
		req.Filename = fmt.Sprintf("session-%s.adi", now.Format("20060102-150405"))
	}

	msg := email.Message{
		To:      req.To,
		Subject: req.Subject,
		Body:    fmt.Sprintf("ADIF for this session attached.\nGenerated by Station Manager at %s.\n", now.Format(time.RFC1123)),
		Attachments: []email.Attachment{{
			Filename:    req.Filename,
			ContentType: "application/x-adif",
			Body:        []byte(req.ADIF),
		}},
	}

	if err := s.mailer.Send(r.Context(), msg); err != nil {
		if stderrs.Is(err, email.ErrMailerDisabled) {
			// Race: operator cleared SMTP config between the
			// Enabled() check above and Send. Same UX as the
			// pre-check path.
			s.writeError(w, http.StatusServiceUnavailable, "mailer_disabled",
				"SMTP is not configured", op)
			return
		}
		if stderrs.Is(err, email.ErrInvalidMessage) {
			s.writeError(w, http.StatusBadRequest, "invalid_field_value",
				err.Error(), op)
			return
		}
		s.logger.ErrorWith().Err(err).Str("to", req.To).Msg("session email send failed")
		s.writeError(w, http.StatusBadGateway, "smtp_failure",
			"SMTP send failed; check daemon logs for the cause", op)
		return
	}

	s.writeJSON(w, http.StatusOK, map[string]string{"status": "sent"})
}
