// Package sqlite is the SQLite persistence layer for the Station Manager
// daemon.
//
// # Service lifecycle
//
// [Service] follows the project's lifecycle convention: Initialize() →
// Open() → use → Close(). All lifecycle methods are idempotent.
// Initialize validates config and ensures the database directory exists.
// Open connects to sqlite, sets PRAGMAs (foreign_keys, WAL, busy_timeout),
// pings, and runs migrations. Close closes the connection.
//
// # Adapter pattern
//
// Domain types ([types.Qso], [types.ContactedStation], etc.) are converted
// to/from sqlboiler model types via the adapters subpackage. The conversion
// uses the additional_data JSON blob pattern: promoted columns (call, band,
// mode, freq, etc.) are authoritative and duplicated in the blob for
// round-trip fidelity. Adding a new ADIF field to types.Qso is a one-line
// change; the adapter carries it through automatically via json.Marshal.
// See docs/v1-analysis/invariants.md → "additional_data absorbs ADIF
// evolution."
//
// # Generated models
//
// Files under models/ are generated by sqlboiler from the schema defined
// in migrations/0001_init.up.sql. Do not hand-edit them; regenerate with
// `sqlboiler sqlite3` from this directory after schema changes.
//
// # API surface
//
// Query methods come in two forms: Foo() (convenience, uses
// context.Background) and FooWithContext() (takes a caller-supplied
// context). The v2 daemon should use the WithContext variants. The
// no-context wrappers exist for v1 compatibility and may be removed
// when no caller uses them.
//
// Transactional variants (InsertQsoTx, UpdateQsoTx, InsertQsoUploadTx)
// accept a caller-supplied *sql.Tx for composing multiple writes in a
// single transaction — the pattern used by qsoservice.Submit() to
// satisfy the one-fails-all-fail invariant.
package sqlite
