package adif

import (
	"strings"
	"testing"

	"github.com/ColonelBlimp/station-manager/internal/types"
)

// ---- Parse: happy path with header and records ------------------------------

func TestParse_FullFileWithHeader(t *testing.T) {
	input := `Generated by test
<ADIF_VER:5>3.1.5
<CREATED_TIMESTAMP:16>20250508T120000Z
<PROGRAMID:2>SM
<PROGRAMVERSION:5>0.0.1
<EOH>
<CALL:5>M0CMC<BAND:3>40m<MODE:3>SSB<FREQ:5>7.050<QSO_DATE:8>20250508<TIME_ON:4>0845<RST_SENT:2>59<RST_RCVD:2>59<STATION_CALLSIGN:5>G4ABC<EOR>
<CALL:6>DL1ABC<BAND:3>20m<MODE:2>CW<QSO_DATE:8>20250509<TIME_ON:4>1430<EOR>
`
	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}

	// Header
	if adif.HeaderSection.ADIFVer != "3.1.5" {
		t.Fatalf("ADIFVer = %q, want %q", adif.HeaderSection.ADIFVer, "3.1.5")
	}
	if adif.HeaderSection.ProgramID != "SM" {
		t.Fatalf("ProgramID = %q, want %q", adif.HeaderSection.ProgramID, "SM")
	}
	if adif.HeaderSection.ProgramVersion != "0.0.1" {
		t.Fatalf("ProgramVersion = %q, want %q", adif.HeaderSection.ProgramVersion, "0.0.1")
	}
	if adif.HeaderSection.CreatedTimestamp != "20250508T120000Z" {
		t.Fatalf("CreatedTimestamp = %q, want %q", adif.HeaderSection.CreatedTimestamp, "20250508T120000Z")
	}

	// Records
	if len(adif.Records) != 2 {
		t.Fatalf("got %d records, want 2", len(adif.Records))
	}

	r0 := adif.Records[0]
	if r0.Call != "M0CMC" {
		t.Fatalf("r0.Call = %q, want %q", r0.Call, "M0CMC")
	}
	if r0.Band != "40m" {
		t.Fatalf("r0.Band = %q, want %q", r0.Band, "40m")
	}
	if r0.Mode != "SSB" {
		t.Fatalf("r0.Mode = %q, want %q", r0.Mode, "SSB")
	}
	if r0.Freq != "7.050" {
		t.Fatalf("r0.Freq = %q, want %q", r0.Freq, "7.050")
	}
	if r0.QsoDate != "20250508" {
		t.Fatalf("r0.QsoDate = %q, want %q", r0.QsoDate, "20250508")
	}
	if r0.TimeOn != "0845" {
		t.Fatalf("r0.TimeOn = %q, want %q", r0.TimeOn, "0845")
	}
	if r0.RstSent != "59" {
		t.Fatalf("r0.RstSent = %q, want %q", r0.RstSent, "59")
	}
	if r0.StationCallsign != "G4ABC" {
		t.Fatalf("r0.StationCallsign = %q, want %q", r0.StationCallsign, "G4ABC")
	}

	r1 := adif.Records[1]
	if r1.Call != "DL1ABC" {
		t.Fatalf("r1.Call = %q, want %q", r1.Call, "DL1ABC")
	}
	if r1.Mode != "CW" {
		t.Fatalf("r1.Mode = %q, want %q", r1.Mode, "CW")
	}
}

// ---- Parse: no header -------------------------------------------------------

func TestParse_NoHeader(t *testing.T) {
	input := `<CALL:5>M0CMC<BAND:3>40m<MODE:3>SSB<EOR>
`
	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if adif.HeaderSection.ADIFVer != "" {
		t.Fatalf("expected empty header, got ADIFVer=%q", adif.HeaderSection.ADIFVer)
	}
	if len(adif.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(adif.Records))
	}
	if adif.Records[0].Call != "M0CMC" {
		t.Fatalf("Call = %q, want %q", adif.Records[0].Call, "M0CMC")
	}
}

// ---- Parse: empty and whitespace input --------------------------------------

func TestParse_EmptyInput(t *testing.T) {
	_, err := Parse([]byte{})
	if err == nil {
		t.Fatal("expected error for empty input, got nil")
	}
}

func TestParse_WhitespaceOnlyAfterHeader(t *testing.T) {
	input := `<ADIF_VER:5>3.1.5<EOH>

`
	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if len(adif.Records) != 0 {
		t.Fatalf("got %d records, want 0", len(adif.Records))
	}
}

// ---- Parse: case insensitivity ----------------------------------------------

func TestParse_CaseInsensitiveTags(t *testing.T) {
	input := `<CaLl:5>M0CMC<bAnD:3>40m<Mode:3>SSB<eor>
`
	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if len(adif.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(adif.Records))
	}
	r := adif.Records[0]
	if r.Call != "M0CMC" {
		t.Fatalf("Call = %q, want %q", r.Call, "M0CMC")
	}
	if r.Band != "40m" {
		t.Fatalf("Band = %q, want %q", r.Band, "40m")
	}
	if r.Mode != "SSB" {
		t.Fatalf("Mode = %q, want %q", r.Mode, "SSB")
	}
}

func TestParse_CaseInsensitiveHeaderAndEOH(t *testing.T) {
	input := `<adif_ver:5>3.1.5<Eoh>
<CALL:5>M0CMC<EOR>
`
	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if adif.HeaderSection.ADIFVer != "3.1.5" {
		t.Fatalf("ADIFVer = %q, want %q", adif.HeaderSection.ADIFVer, "3.1.5")
	}
	if len(adif.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(adif.Records))
	}
}

// ---- Parse: unknown fields are silently ignored -----------------------------

func TestParse_UnknownFieldsIgnored(t *testing.T) {
	input := `<CALL:5>M0CMC<UNKNOWN_TAG:3>foo<BAND:3>40m<ANOTHER:4>blah<EOR>
`
	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if len(adif.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(adif.Records))
	}
	r := adif.Records[0]
	if r.Call != "M0CMC" {
		t.Fatalf("Call = %q, want %q", r.Call, "M0CMC")
	}
	if r.Band != "40m" {
		t.Fatalf("Band = %q, want %q", r.Band, "40m")
	}
}

// ---- Round-trip: QsoToRecord → String → Parse → verify ----------------------

func TestRoundTrip_QsoToRecordStringParse(t *testing.T) {
	rec := Record{}
	rec.Call = "M0CMC"
	rec.Band = "40m"
	rec.Mode = "SSB"
	rec.Freq = "7050000" // Hz integer — formatField converts to MHz
	rec.QsoDate = "2025-05-08"
	rec.TimeOn = "08:45"
	rec.RstSent = "59"
	rec.RstRcvd = "59"
	rec.StationCallsign = "G4ABC"
	rec.Name = "Marc"
	rec.Comment = "Nice QSO"

	adifStr := rec.String()

	// Parse the serialised output back
	parsed, err := Parse([]byte(adifStr))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if len(parsed.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(parsed.Records))
	}

	r := parsed.Records[0]

	// Verify fields survive the round-trip. Note: formatField normalises
	// dates (strip dashes), times (strip colons), and frequencies (Hz→MHz),
	// so the parsed values reflect the ADIF-canonical form, not the input.
	if r.Call != "M0CMC" {
		t.Fatalf("Call = %q, want %q", r.Call, "M0CMC")
	}
	if r.Band != "40m" {
		t.Fatalf("Band = %q, want %q", r.Band, "40m")
	}
	if r.Mode != "SSB" {
		t.Fatalf("Mode = %q, want %q", r.Mode, "SSB")
	}
	if r.QsoDate != "20250508" {
		t.Fatalf("QsoDate = %q, want %q", r.QsoDate, "20250508")
	}
	if r.TimeOn != "0845" {
		t.Fatalf("TimeOn = %q, want %q", r.TimeOn, "0845")
	}
	if r.RstSent != "59" {
		t.Fatalf("RstSent = %q, want %q", r.RstSent, "59")
	}
	if r.StationCallsign != "G4ABC" {
		t.Fatalf("StationCallsign = %q, want %q", r.StationCallsign, "G4ABC")
	}
	if r.Name != "Marc" {
		t.Fatalf("Name = %q, want %q", r.Name, "Marc")
	}
	if r.Comment != "Nice QSO" {
		t.Fatalf("Comment = %q, want %q", r.Comment, "Nice QSO")
	}

	// Freq: 7050000 → "7.050" (Hz to MHz conversion)
	if r.Freq != "7.050" {
		t.Fatalf("Freq = %q, want %q", r.Freq, "7.050")
	}
}

// ---- Parse: multiple records without trailing EOR ---------------------------

func TestParse_TrailingRecordWithoutEOR(t *testing.T) {
	// Some ADIF exporters omit the final <EOR>. The parser should still
	// pick up the trailing block if it contains valid fields.
	input := `<CALL:5>M0CMC<BAND:3>40m<EOR>
<CALL:6>DL1ABC<BAND:3>20m`

	adif, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse returned error: %v", err)
	}
	if len(adif.Records) != 2 {
		t.Fatalf("got %d records, want 2", len(adif.Records))
	}
	if adif.Records[1].Call != "DL1ABC" {
		t.Fatalf("r1.Call = %q, want %q", adif.Records[1].Call, "DL1ABC")
	}
}

// ---- ComposeToAdifString ----------------------------------------------------

func TestComposeToAdifString_EmptySlice(t *testing.T) {
	_, err := ComposeToAdifString(nil)
	if err == nil {
		t.Fatal("expected error for empty slice, got nil")
	}
}

func TestComposeToAdifString_ProducesHeaderAndRecords(t *testing.T) {
	slice := types.QsoSlice{
		{
			QsoDetails:       types.QsoDetails{Band: "40m", Mode: "SSB", QsoDate: "20250508", TimeOn: "0845"},
			ContactedStation: types.ContactedStation{Call: "M0CMC"},
			LoggingStation:   types.LoggingStation{StationCallsign: "G4ABC"},
		},
	}
	out, err := ComposeToAdifString(slice)
	if err != nil {
		t.Fatalf("ComposeToAdifString returned error: %v", err)
	}
	if !strings.Contains(out, EohStr) {
		t.Fatal("output missing <EOH>")
	}
	if !strings.Contains(out, EorStr) {
		t.Fatal("output missing <EOR>")
	}
	if !strings.Contains(out, "<CALL:5>M0CMC") {
		t.Fatal("output missing CALL field")
	}
}

// ---- H2: <EOR>/<EOH> inside a field value must not split the record --------

// TestParse_EorInFieldValueRoundTrips builds a record whose free-text fields
// contain the literal marker text, emits it, and parses it back. The length
// prefix — not the marker text — governs where each value ends, so the record
// must survive as ONE record with the values intact (review 2026-06-04 H2).
func TestParse_EorInFieldValueRoundTrips(t *testing.T) {
	rec := Record{}
	rec.Call = "M0CMC"
	rec.Band = "40m"
	rec.Comment = "contains <EOR> and <EOH> tokens"
	rec.Notes = "trailing marker <EOR>"

	parsed, err := Parse([]byte(rec.String()))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(parsed.Records) != 1 {
		t.Fatalf("got %d records, want 1 (a marker inside a value must not split)", len(parsed.Records))
	}
	r := parsed.Records[0]
	if r.Call != "M0CMC" {
		t.Errorf("Call = %q, want M0CMC", r.Call)
	}
	if r.Comment != "contains <EOR> and <EOH> tokens" {
		t.Errorf("Comment = %q, want it intact", r.Comment)
	}
	if r.Notes != "trailing marker <EOR>" {
		t.Errorf("Notes = %q, want it intact", r.Notes)
	}
}

// TestParse_EorInValueDoesNotSplit_Handcrafted pins the exact wire shape the
// old marker-first splitter mis-handled: COMMENT's declared length (20) spans
// the literal "<EOR>", and a real BAND + <EOR> follow. The fields after the
// marker-bearing value must still parse into the same record.
func TestParse_EorInValueDoesNotSplit_Handcrafted(t *testing.T) {
	// "contains <EOR> token" is exactly 20 bytes.
	input := "<CALL:5>M0CMC<COMMENT:20>contains <EOR> token<BAND:3>40m<EOR>"
	parsed, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(parsed.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(parsed.Records))
	}
	r := parsed.Records[0]
	if r.Call != "M0CMC" || r.Comment != "contains <EOR> token" || r.Band != "40m" {
		t.Errorf("mis-parsed: Call=%q Comment=%q Band=%q", r.Call, r.Comment, r.Band)
	}
}

// ---- L1: tolerant truncation of an over-long declared length ----------------

// TestParse_OverlongFieldLengthTruncatesTolerantly documents the parser's
// tolerant behaviour: a declared length that overruns the buffer takes the
// available bytes and returns no error (review 2026-06-04 L1). This is a
// characterization test — if a future strict/import mode is added, it should
// surface this condition rather than silently truncate.
func TestParse_OverlongFieldLengthTruncatesTolerantly(t *testing.T) {
	input := "<CALL:99>M0CMC"
	parsed, err := Parse([]byte(input))
	if err != nil {
		t.Fatalf("Parse: %v", err)
	}
	if len(parsed.Records) != 1 {
		t.Fatalf("got %d records, want 1", len(parsed.Records))
	}
	if parsed.Records[0].Call != "M0CMC" {
		t.Errorf("Call = %q, want M0CMC (truncated to available bytes)", parsed.Records[0].Call)
	}
}

// ---- M2: bulk-parse allocation guard ---------------------------------------

// BenchmarkParse_ManyRecords guards against an allocation regression in the
// multi-record path (review 2026-06-04 M2 — the old splitter lowercased the
// whole remaining file once per record, O(file × records)). Run with
// `go test -bench=Parse_ManyRecords -benchmem ./internal/adif`.
func BenchmarkParse_ManyRecords(b *testing.B) {
	var sb strings.Builder
	const rec = "<CALL:5>M0CMC<BAND:3>40m<MODE:3>SSB<FREQ:6>14.074" +
		"<QSO_DATE:8>20250508<TIME_ON:4>0845<STATION_CALLSIGN:5>G4ABC<EOR>\n"
	for i := 0; i < 5000; i++ {
		sb.WriteString(rec)
	}
	data := []byte(sb.String())

	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		got, err := Parse(data)
		if err != nil {
			b.Fatal(err)
		}
		if len(got.Records) != 5000 {
			b.Fatalf("got %d records, want 5000", len(got.Records))
		}
	}
}
