// Package manual embeds the built operator manual into the daemon binary.
//
// The manual is a single self-contained, zero-JS static page generated by Hugo
// from the per-chapter markdown in this directory (ADR 0036). This directory is
// therefore both a Hugo project (content/, layouts/, hugo.toml) and a one-file
// Go package: Go compiles only embed.go and ignores the Hugo tree, so the two
// coexist and the manual stays cohesive under a single top-level path.
//
// Build pipeline: `task manual:build` (and the rpm/release scripts) run `hugo`
// to populate public/ before `go build` reaches the embed directive. public/ is
// not committed except a placeholder index.html, so the package compiles before
// Hugo has ever run (mirrors the SPA dist/index.html placeholder). The same
// public/ is also shipped on disk in the RPM so the manual is readable from
// file:// when the daemon is down.
package manual

import (
	"embed"
	"io/fs"
)

// site holds the built manual's static files. The `all:` prefix picks up
// dot-prefixed files (Hugo emits none today, but keeps the embed honest if a
// future asset like .well-known/ appears).
//
//go:embed all:public
var site embed.FS

// FS returns the manual's filesystem rooted at public/ so a file server treats
// index.html as the root document.
//
// fs.Sub on a hard-coded valid path is infallible at runtime; a missing public/
// directory at compile time fails the Go build, not this call (the committed
// placeholder index.html prevents that). The function therefore returns only
// fs.FS — no error to plumb, matching frontend.LoggingFS et al.
func FS() fs.FS {
	sub, err := fs.Sub(site, "public")
	if err != nil {
		// Unreachable: the embed directive guarantees public/ exists and is
		// well-formed. Panicking surfaces a programmer error in the embed
		// directive loudly rather than silently serving nothing.
		panic("manual: fs.Sub on embedded site failed: " + err.Error())
	}
	return sub
}
