// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ArchiveMetadatum is an object representing the database table.
type ArchiveMetadatum struct {
	Singleton        int64      `boil:"singleton" json:"singleton" toml:"singleton" yaml:"singleton"`
	ArchiveUUID      string     `boil:"archive_uuid" json:"archive_uuid" toml:"archive_uuid" yaml:"archive_uuid"`
	CreatedAt        time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	DefaultLogbookID null.Int64 `boil:"default_logbook_id" json:"default_logbook_id,omitempty" toml:"default_logbook_id" yaml:"default_logbook_id,omitempty"`

	R *archiveMetadatumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L archiveMetadatumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ArchiveMetadatumColumns = struct {
	Singleton        string
	ArchiveUUID      string
	CreatedAt        string
	DefaultLogbookID string
}{
	Singleton:        "singleton",
	ArchiveUUID:      "archive_uuid",
	CreatedAt:        "created_at",
	DefaultLogbookID: "default_logbook_id",
}

var ArchiveMetadatumTableColumns = struct {
	Singleton        string
	ArchiveUUID      string
	CreatedAt        string
	DefaultLogbookID string
}{
	Singleton:        "archive_metadata.singleton",
	ArchiveUUID:      "archive_metadata.archive_uuid",
	CreatedAt:        "archive_metadata.created_at",
	DefaultLogbookID: "archive_metadata.default_logbook_id",
}

// Generated where

type whereHelperint64 struct{ field string }

func (w whereHelperint64) EQ(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint64) NEQ(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint64) LT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint64) LTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint64) GT(x int64) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint64) GTE(x int64) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod   { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod  { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

type whereHelpertime_Time struct{ field string }

func (w whereHelpertime_Time) EQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertime_Time) NEQ(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertime_Time) LT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertime_Time) LTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertime_Time) GT(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertime_Time) GTE(x time.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Int64 struct{ field string }

func (w whereHelpernull_Int64) EQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int64) NEQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int64) LT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int64) LTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int64) GT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int64) GTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var ArchiveMetadatumWhere = struct {
	Singleton        whereHelperint64
	ArchiveUUID      whereHelperstring
	CreatedAt        whereHelpertime_Time
	DefaultLogbookID whereHelpernull_Int64
}{
	Singleton:        whereHelperint64{field: "\"archive_metadata\".\"singleton\""},
	ArchiveUUID:      whereHelperstring{field: "\"archive_metadata\".\"archive_uuid\""},
	CreatedAt:        whereHelpertime_Time{field: "\"archive_metadata\".\"created_at\""},
	DefaultLogbookID: whereHelpernull_Int64{field: "\"archive_metadata\".\"default_logbook_id\""},
}

// ArchiveMetadatumRels is where relationship names are stored.
var ArchiveMetadatumRels = struct {
	DefaultLogbook string
}{
	DefaultLogbook: "DefaultLogbook",
}

// archiveMetadatumR is where relationships are stored.
type archiveMetadatumR struct {
	DefaultLogbook *Logbook `boil:"DefaultLogbook" json:"DefaultLogbook" toml:"DefaultLogbook" yaml:"DefaultLogbook"`
}

// NewStruct creates a new relationship struct
func (*archiveMetadatumR) NewStruct() *archiveMetadatumR {
	return &archiveMetadatumR{}
}

func (o *ArchiveMetadatum) GetDefaultLogbook() *Logbook {
	if o == nil {
		return nil
	}

	return o.R.GetDefaultLogbook()
}

func (r *archiveMetadatumR) GetDefaultLogbook() *Logbook {
	if r == nil {
		return nil
	}

	return r.DefaultLogbook
}

// archiveMetadatumL is where Load methods for each relationship are stored.
type archiveMetadatumL struct{}

var (
	archiveMetadatumAllColumns            = []string{"singleton", "archive_uuid", "created_at", "default_logbook_id"}
	archiveMetadatumColumnsWithoutDefault = []string{"archive_uuid"}
	archiveMetadatumColumnsWithDefault    = []string{"singleton", "created_at", "default_logbook_id"}
	archiveMetadatumPrimaryKeyColumns     = []string{"singleton"}
	archiveMetadatumGeneratedColumns      = []string{"singleton"}
)

type (
	// ArchiveMetadatumSlice is an alias for a slice of pointers to ArchiveMetadatum.
	// This should almost always be used instead of []ArchiveMetadatum.
	ArchiveMetadatumSlice []*ArchiveMetadatum

	archiveMetadatumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	archiveMetadatumType                 = reflect.TypeOf(&ArchiveMetadatum{})
	archiveMetadatumMapping              = queries.MakeStructMapping(archiveMetadatumType)
	archiveMetadatumPrimaryKeyMapping, _ = queries.BindMapping(archiveMetadatumType, archiveMetadatumMapping, archiveMetadatumPrimaryKeyColumns)
	archiveMetadatumInsertCacheMut       sync.RWMutex
	archiveMetadatumInsertCache          = make(map[string]insertCache)
	archiveMetadatumUpdateCacheMut       sync.RWMutex
	archiveMetadatumUpdateCache          = make(map[string]updateCache)
	archiveMetadatumUpsertCacheMut       sync.RWMutex
	archiveMetadatumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single archiveMetadatum record from the query.
func (q archiveMetadatumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ArchiveMetadatum, error) {
	o := &ArchiveMetadatum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for archive_metadata")
	}

	return o, nil
}

// All returns all ArchiveMetadatum records from the query.
func (q archiveMetadatumQuery) All(ctx context.Context, exec boil.ContextExecutor) (ArchiveMetadatumSlice, error) {
	var o []*ArchiveMetadatum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ArchiveMetadatum slice")
	}

	return o, nil
}

// Count returns the count of all ArchiveMetadatum records in the query.
func (q archiveMetadatumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count archive_metadata rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q archiveMetadatumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if archive_metadata exists")
	}

	return count > 0, nil
}

// DefaultLogbook pointed to by the foreign key.
func (o *ArchiveMetadatum) DefaultLogbook(mods ...qm.QueryMod) logbookQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DefaultLogbookID),
	}

	queryMods = append(queryMods, mods...)

	return Logbooks(queryMods...)
}

// LoadDefaultLogbook allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (archiveMetadatumL) LoadDefaultLogbook(ctx context.Context, e boil.ContextExecutor, singular bool, maybeArchiveMetadatum any, mods queries.Applicator) error {
	var slice []*ArchiveMetadatum
	var object *ArchiveMetadatum

	if singular {
		var ok bool
		object, ok = maybeArchiveMetadatum.(*ArchiveMetadatum)
		if !ok {
			object = new(ArchiveMetadatum)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeArchiveMetadatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeArchiveMetadatum))
			}
		}
	} else {
		s, ok := maybeArchiveMetadatum.(*[]*ArchiveMetadatum)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeArchiveMetadatum)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeArchiveMetadatum))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &archiveMetadatumR{}
		}
		if !queries.IsNil(object.DefaultLogbookID) {
			args[object.DefaultLogbookID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &archiveMetadatumR{}
			}

			if !queries.IsNil(obj.DefaultLogbookID) {
				args[obj.DefaultLogbookID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`logbook`),
		qm.WhereIn(`logbook.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`logbook.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Logbook")
	}

	var resultSlice []*Logbook
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Logbook")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for logbook")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for logbook")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.DefaultLogbook = foreign
		if foreign.R == nil {
			foreign.R = &logbookR{}
		}
		foreign.R.DefaultLogbookArchiveMetadata = append(foreign.R.DefaultLogbookArchiveMetadata, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.DefaultLogbookID, foreign.ID) {
				local.R.DefaultLogbook = foreign
				if foreign.R == nil {
					foreign.R = &logbookR{}
				}
				foreign.R.DefaultLogbookArchiveMetadata = append(foreign.R.DefaultLogbookArchiveMetadata, local)
				break
			}
		}
	}

	return nil
}

// SetDefaultLogbook of the archiveMetadatum to the related item.
// Sets o.R.DefaultLogbook to related.
// Adds o to related.R.DefaultLogbookArchiveMetadata.
func (o *ArchiveMetadatum) SetDefaultLogbook(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Logbook) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"archive_metadata\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"default_logbook_id"}),
		strmangle.WhereClause("\"", "\"", 0, archiveMetadatumPrimaryKeyColumns),
	)
	values := []any{related.ID, o.Singleton}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.DefaultLogbookID, related.ID)
	if o.R == nil {
		o.R = &archiveMetadatumR{
			DefaultLogbook: related,
		}
	} else {
		o.R.DefaultLogbook = related
	}

	if related.R == nil {
		related.R = &logbookR{
			DefaultLogbookArchiveMetadata: ArchiveMetadatumSlice{o},
		}
	} else {
		related.R.DefaultLogbookArchiveMetadata = append(related.R.DefaultLogbookArchiveMetadata, o)
	}

	return nil
}

// RemoveDefaultLogbook relationship.
// Sets o.R.DefaultLogbook to nil.
// Removes o from all passed in related items' relationships struct.
func (o *ArchiveMetadatum) RemoveDefaultLogbook(ctx context.Context, exec boil.ContextExecutor, related *Logbook) error {
	var err error

	queries.SetScanner(&o.DefaultLogbookID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("default_logbook_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.DefaultLogbook = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DefaultLogbookArchiveMetadata {
		if queries.Equal(o.DefaultLogbookID, ri.DefaultLogbookID) {
			continue
		}

		ln := len(related.R.DefaultLogbookArchiveMetadata)
		if ln > 1 && i < ln-1 {
			related.R.DefaultLogbookArchiveMetadata[i] = related.R.DefaultLogbookArchiveMetadata[ln-1]
		}
		related.R.DefaultLogbookArchiveMetadata = related.R.DefaultLogbookArchiveMetadata[:ln-1]
		break
	}
	return nil
}

// ArchiveMetadata retrieves all the records using an executor.
func ArchiveMetadata(mods ...qm.QueryMod) archiveMetadatumQuery {
	mods = append(mods, qm.From("\"archive_metadata\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"archive_metadata\".*"})
	}

	return archiveMetadatumQuery{q}
}

// FindArchiveMetadatum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindArchiveMetadatum(ctx context.Context, exec boil.ContextExecutor, singleton int64, selectCols ...string) (*ArchiveMetadatum, error) {
	archiveMetadatumObj := &ArchiveMetadatum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"archive_metadata\" where \"singleton\"=?", sel,
	)

	q := queries.Raw(query, singleton)

	err := q.Bind(ctx, exec, archiveMetadatumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from archive_metadata")
	}

	return archiveMetadatumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ArchiveMetadatum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no archive_metadata provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(archiveMetadatumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	archiveMetadatumInsertCacheMut.RLock()
	cache, cached := archiveMetadatumInsertCache[key]
	archiveMetadatumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			archiveMetadatumAllColumns,
			archiveMetadatumColumnsWithDefault,
			archiveMetadatumColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, archiveMetadatumGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(archiveMetadatumType, archiveMetadatumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(archiveMetadatumType, archiveMetadatumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"archive_metadata\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"archive_metadata\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into archive_metadata")
	}

	if !cached {
		archiveMetadatumInsertCacheMut.Lock()
		archiveMetadatumInsertCache[key] = cache
		archiveMetadatumInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the ArchiveMetadatum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ArchiveMetadatum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	archiveMetadatumUpdateCacheMut.RLock()
	cache, cached := archiveMetadatumUpdateCache[key]
	archiveMetadatumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			archiveMetadatumAllColumns,
			archiveMetadatumPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, archiveMetadatumGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update archive_metadata, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"archive_metadata\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, archiveMetadatumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(archiveMetadatumType, archiveMetadatumMapping, append(wl, archiveMetadatumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update archive_metadata row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for archive_metadata")
	}

	if !cached {
		archiveMetadatumUpdateCacheMut.Lock()
		archiveMetadatumUpdateCache[key] = cache
		archiveMetadatumUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q archiveMetadatumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for archive_metadata")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for archive_metadata")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ArchiveMetadatumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), archiveMetadatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"archive_metadata\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, archiveMetadatumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in archiveMetadatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all archiveMetadatum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ArchiveMetadatum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no archive_metadata provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(archiveMetadatumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	archiveMetadatumUpsertCacheMut.RLock()
	cache, cached := archiveMetadatumUpsertCache[key]
	archiveMetadatumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			archiveMetadatumAllColumns,
			archiveMetadatumColumnsWithDefault,
			archiveMetadatumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			archiveMetadatumAllColumns,
			archiveMetadatumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert archive_metadata, could not build update column list")
		}

		ret := strmangle.SetComplement(archiveMetadatumAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(archiveMetadatumPrimaryKeyColumns))
			copy(conflict, archiveMetadatumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"archive_metadata\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(archiveMetadatumType, archiveMetadatumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(archiveMetadatumType, archiveMetadatumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert archive_metadata")
	}

	if !cached {
		archiveMetadatumUpsertCacheMut.Lock()
		archiveMetadatumUpsertCache[key] = cache
		archiveMetadatumUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single ArchiveMetadatum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ArchiveMetadatum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ArchiveMetadatum provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), archiveMetadatumPrimaryKeyMapping)
	sql := "DELETE FROM \"archive_metadata\" WHERE \"singleton\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from archive_metadata")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for archive_metadata")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q archiveMetadatumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no archiveMetadatumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from archive_metadata")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for archive_metadata")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ArchiveMetadatumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), archiveMetadatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"archive_metadata\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, archiveMetadatumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from archiveMetadatum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for archive_metadata")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ArchiveMetadatum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindArchiveMetadatum(ctx, exec, o.Singleton)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ArchiveMetadatumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ArchiveMetadatumSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), archiveMetadatumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"archive_metadata\".* FROM \"archive_metadata\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, archiveMetadatumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ArchiveMetadatumSlice")
	}

	*o = slice

	return nil
}

// ArchiveMetadatumExists checks if the ArchiveMetadatum row exists.
func ArchiveMetadatumExists(ctx context.Context, exec boil.ContextExecutor, singleton int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"archive_metadata\" where \"singleton\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, singleton)
	}
	row := exec.QueryRowContext(ctx, sql, singleton)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if archive_metadata exists")
	}

	return exists, nil
}

// Exists checks if the ArchiveMetadatum row exists.
func (o *ArchiveMetadatum) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ArchiveMetadatumExists(ctx, exec, o.Singleton)
}
