// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// LogbookDestination is an object representing the database table.
type LogbookDestination struct {
	ID              int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt       time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	ModifiedAt      null.Time   `boil:"modified_at" json:"modified_at,omitempty" toml:"modified_at" yaml:"modified_at,omitempty"`
	LogbookID       int64       `boil:"logbook_id" json:"logbook_id" toml:"logbook_id" yaml:"logbook_id"`
	Destination     string      `boil:"destination" json:"destination" toml:"destination" yaml:"destination"`
	ForwarderName   string      `boil:"forwarder_name" json:"forwarder_name" toml:"forwarder_name" yaml:"forwarder_name"`
	Enabled         int64       `boil:"enabled" json:"enabled" toml:"enabled" yaml:"enabled"`
	Credentials     null.String `boil:"credentials" json:"credentials,omitempty" toml:"credentials" yaml:"credentials,omitempty"`
	RemoteAdoptedAt null.Time   `boil:"remote_adopted_at" json:"remote_adopted_at,omitempty" toml:"remote_adopted_at" yaml:"remote_adopted_at,omitempty"`

	R *logbookDestinationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L logbookDestinationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LogbookDestinationColumns = struct {
	ID              string
	CreatedAt       string
	ModifiedAt      string
	LogbookID       string
	Destination     string
	ForwarderName   string
	Enabled         string
	Credentials     string
	RemoteAdoptedAt string
}{
	ID:              "id",
	CreatedAt:       "created_at",
	ModifiedAt:      "modified_at",
	LogbookID:       "logbook_id",
	Destination:     "destination",
	ForwarderName:   "forwarder_name",
	Enabled:         "enabled",
	Credentials:     "credentials",
	RemoteAdoptedAt: "remote_adopted_at",
}

var LogbookDestinationTableColumns = struct {
	ID              string
	CreatedAt       string
	ModifiedAt      string
	LogbookID       string
	Destination     string
	ForwarderName   string
	Enabled         string
	Credentials     string
	RemoteAdoptedAt string
}{
	ID:              "logbook_destination.id",
	CreatedAt:       "logbook_destination.created_at",
	ModifiedAt:      "logbook_destination.modified_at",
	LogbookID:       "logbook_destination.logbook_id",
	Destination:     "logbook_destination.destination",
	ForwarderName:   "logbook_destination.forwarder_name",
	Enabled:         "logbook_destination.enabled",
	Credentials:     "logbook_destination.credentials",
	RemoteAdoptedAt: "logbook_destination.remote_adopted_at",
}

// Generated where

var LogbookDestinationWhere = struct {
	ID              whereHelperint64
	CreatedAt       whereHelpertime_Time
	ModifiedAt      whereHelpernull_Time
	LogbookID       whereHelperint64
	Destination     whereHelperstring
	ForwarderName   whereHelperstring
	Enabled         whereHelperint64
	Credentials     whereHelpernull_String
	RemoteAdoptedAt whereHelpernull_Time
}{
	ID:              whereHelperint64{field: "\"logbook_destination\".\"id\""},
	CreatedAt:       whereHelpertime_Time{field: "\"logbook_destination\".\"created_at\""},
	ModifiedAt:      whereHelpernull_Time{field: "\"logbook_destination\".\"modified_at\""},
	LogbookID:       whereHelperint64{field: "\"logbook_destination\".\"logbook_id\""},
	Destination:     whereHelperstring{field: "\"logbook_destination\".\"destination\""},
	ForwarderName:   whereHelperstring{field: "\"logbook_destination\".\"forwarder_name\""},
	Enabled:         whereHelperint64{field: "\"logbook_destination\".\"enabled\""},
	Credentials:     whereHelpernull_String{field: "\"logbook_destination\".\"credentials\""},
	RemoteAdoptedAt: whereHelpernull_Time{field: "\"logbook_destination\".\"remote_adopted_at\""},
}

// LogbookDestinationRels is where relationship names are stored.
var LogbookDestinationRels = struct {
	Logbook string
}{
	Logbook: "Logbook",
}

// logbookDestinationR is where relationships are stored.
type logbookDestinationR struct {
	Logbook *Logbook `boil:"Logbook" json:"Logbook" toml:"Logbook" yaml:"Logbook"`
}

// NewStruct creates a new relationship struct
func (*logbookDestinationR) NewStruct() *logbookDestinationR {
	return &logbookDestinationR{}
}

func (o *LogbookDestination) GetLogbook() *Logbook {
	if o == nil {
		return nil
	}

	return o.R.GetLogbook()
}

func (r *logbookDestinationR) GetLogbook() *Logbook {
	if r == nil {
		return nil
	}

	return r.Logbook
}

// logbookDestinationL is where Load methods for each relationship are stored.
type logbookDestinationL struct{}

var (
	logbookDestinationAllColumns            = []string{"id", "created_at", "modified_at", "logbook_id", "destination", "forwarder_name", "enabled", "credentials", "remote_adopted_at"}
	logbookDestinationColumnsWithoutDefault = []string{"logbook_id", "destination", "forwarder_name"}
	logbookDestinationColumnsWithDefault    = []string{"id", "created_at", "modified_at", "enabled", "credentials", "remote_adopted_at"}
	logbookDestinationPrimaryKeyColumns     = []string{"id"}
	logbookDestinationGeneratedColumns      = []string{"id"}
)

type (
	// LogbookDestinationSlice is an alias for a slice of pointers to LogbookDestination.
	// This should almost always be used instead of []LogbookDestination.
	LogbookDestinationSlice []*LogbookDestination

	logbookDestinationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	logbookDestinationType                 = reflect.TypeOf(&LogbookDestination{})
	logbookDestinationMapping              = queries.MakeStructMapping(logbookDestinationType)
	logbookDestinationPrimaryKeyMapping, _ = queries.BindMapping(logbookDestinationType, logbookDestinationMapping, logbookDestinationPrimaryKeyColumns)
	logbookDestinationInsertCacheMut       sync.RWMutex
	logbookDestinationInsertCache          = make(map[string]insertCache)
	logbookDestinationUpdateCacheMut       sync.RWMutex
	logbookDestinationUpdateCache          = make(map[string]updateCache)
	logbookDestinationUpsertCacheMut       sync.RWMutex
	logbookDestinationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single logbookDestination record from the query.
func (q logbookDestinationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*LogbookDestination, error) {
	o := &LogbookDestination{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for logbook_destination")
	}

	return o, nil
}

// All returns all LogbookDestination records from the query.
func (q logbookDestinationQuery) All(ctx context.Context, exec boil.ContextExecutor) (LogbookDestinationSlice, error) {
	var o []*LogbookDestination

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to LogbookDestination slice")
	}

	return o, nil
}

// Count returns the count of all LogbookDestination records in the query.
func (q logbookDestinationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count logbook_destination rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q logbookDestinationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if logbook_destination exists")
	}

	return count > 0, nil
}

// Logbook pointed to by the foreign key.
func (o *LogbookDestination) Logbook(mods ...qm.QueryMod) logbookQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.LogbookID),
	}

	queryMods = append(queryMods, mods...)

	return Logbooks(queryMods...)
}

// LoadLogbook allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (logbookDestinationL) LoadLogbook(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLogbookDestination any, mods queries.Applicator) error {
	var slice []*LogbookDestination
	var object *LogbookDestination

	if singular {
		var ok bool
		object, ok = maybeLogbookDestination.(*LogbookDestination)
		if !ok {
			object = new(LogbookDestination)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLogbookDestination)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLogbookDestination))
			}
		}
	} else {
		s, ok := maybeLogbookDestination.(*[]*LogbookDestination)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLogbookDestination)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLogbookDestination))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &logbookDestinationR{}
		}
		args[object.LogbookID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &logbookDestinationR{}
			}

			args[obj.LogbookID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`logbook`),
		qm.WhereIn(`logbook.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`logbook.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Logbook")
	}

	var resultSlice []*Logbook
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Logbook")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for logbook")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for logbook")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Logbook = foreign
		if foreign.R == nil {
			foreign.R = &logbookR{}
		}
		foreign.R.LogbookDestinations = append(foreign.R.LogbookDestinations, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LogbookID == foreign.ID {
				local.R.Logbook = foreign
				if foreign.R == nil {
					foreign.R = &logbookR{}
				}
				foreign.R.LogbookDestinations = append(foreign.R.LogbookDestinations, local)
				break
			}
		}
	}

	return nil
}

// SetLogbook of the logbookDestination to the related item.
// Sets o.R.Logbook to related.
// Adds o to related.R.LogbookDestinations.
func (o *LogbookDestination) SetLogbook(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Logbook) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"logbook_destination\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"logbook_id"}),
		strmangle.WhereClause("\"", "\"", 0, logbookDestinationPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LogbookID = related.ID
	if o.R == nil {
		o.R = &logbookDestinationR{
			Logbook: related,
		}
	} else {
		o.R.Logbook = related
	}

	if related.R == nil {
		related.R = &logbookR{
			LogbookDestinations: LogbookDestinationSlice{o},
		}
	} else {
		related.R.LogbookDestinations = append(related.R.LogbookDestinations, o)
	}

	return nil
}

// LogbookDestinations retrieves all the records using an executor.
func LogbookDestinations(mods ...qm.QueryMod) logbookDestinationQuery {
	mods = append(mods, qm.From("\"logbook_destination\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"logbook_destination\".*"})
	}

	return logbookDestinationQuery{q}
}

// FindLogbookDestination retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLogbookDestination(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*LogbookDestination, error) {
	logbookDestinationObj := &LogbookDestination{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"logbook_destination\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, logbookDestinationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from logbook_destination")
	}

	return logbookDestinationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *LogbookDestination) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no logbook_destination provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(logbookDestinationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	logbookDestinationInsertCacheMut.RLock()
	cache, cached := logbookDestinationInsertCache[key]
	logbookDestinationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			logbookDestinationAllColumns,
			logbookDestinationColumnsWithDefault,
			logbookDestinationColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, logbookDestinationGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(logbookDestinationType, logbookDestinationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(logbookDestinationType, logbookDestinationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"logbook_destination\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"logbook_destination\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into logbook_destination")
	}

	if !cached {
		logbookDestinationInsertCacheMut.Lock()
		logbookDestinationInsertCache[key] = cache
		logbookDestinationInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the LogbookDestination.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *LogbookDestination) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	logbookDestinationUpdateCacheMut.RLock()
	cache, cached := logbookDestinationUpdateCache[key]
	logbookDestinationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			logbookDestinationAllColumns,
			logbookDestinationPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, logbookDestinationGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update logbook_destination, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"logbook_destination\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, logbookDestinationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(logbookDestinationType, logbookDestinationMapping, append(wl, logbookDestinationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update logbook_destination row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for logbook_destination")
	}

	if !cached {
		logbookDestinationUpdateCacheMut.Lock()
		logbookDestinationUpdateCache[key] = cache
		logbookDestinationUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q logbookDestinationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for logbook_destination")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for logbook_destination")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LogbookDestinationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), logbookDestinationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"logbook_destination\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, logbookDestinationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in logbookDestination slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all logbookDestination")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *LogbookDestination) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no logbook_destination provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(logbookDestinationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	logbookDestinationUpsertCacheMut.RLock()
	cache, cached := logbookDestinationUpsertCache[key]
	logbookDestinationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			logbookDestinationAllColumns,
			logbookDestinationColumnsWithDefault,
			logbookDestinationColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			logbookDestinationAllColumns,
			logbookDestinationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert logbook_destination, could not build update column list")
		}

		ret := strmangle.SetComplement(logbookDestinationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(logbookDestinationPrimaryKeyColumns))
			copy(conflict, logbookDestinationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"logbook_destination\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(logbookDestinationType, logbookDestinationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(logbookDestinationType, logbookDestinationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert logbook_destination")
	}

	if !cached {
		logbookDestinationUpsertCacheMut.Lock()
		logbookDestinationUpsertCache[key] = cache
		logbookDestinationUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single LogbookDestination record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *LogbookDestination) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no LogbookDestination provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), logbookDestinationPrimaryKeyMapping)
	sql := "DELETE FROM \"logbook_destination\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from logbook_destination")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for logbook_destination")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q logbookDestinationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no logbookDestinationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from logbook_destination")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for logbook_destination")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LogbookDestinationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), logbookDestinationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"logbook_destination\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, logbookDestinationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from logbookDestination slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for logbook_destination")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *LogbookDestination) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLogbookDestination(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LogbookDestinationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LogbookDestinationSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), logbookDestinationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"logbook_destination\".* FROM \"logbook_destination\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, logbookDestinationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in LogbookDestinationSlice")
	}

	*o = slice

	return nil
}

// LogbookDestinationExists checks if the LogbookDestination row exists.
func LogbookDestinationExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"logbook_destination\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if logbook_destination exists")
	}

	return exists, nil
}

// Exists checks if the LogbookDestination row exists.
func (o *LogbookDestination) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LogbookDestinationExists(ctx, exec, o.ID)
}
