// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// OperatorEvent is an object representing the database table.
type OperatorEvent struct {
	ID         int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Category   string     `boil:"category" json:"category" toml:"category" yaml:"category"`
	Kind       string     `boil:"kind" json:"kind" toml:"kind" yaml:"kind"`
	Severity   string     `boil:"severity" json:"severity" toml:"severity" yaml:"severity"`
	OccurredAt time.Time  `boil:"occurred_at" json:"occurred_at" toml:"occurred_at" yaml:"occurred_at"`
	Build      string     `boil:"build" json:"build" toml:"build" yaml:"build"`
	Detail     types.JSON `boil:"detail" json:"detail" toml:"detail" yaml:"detail"`

	R *operatorEventR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L operatorEventL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var OperatorEventColumns = struct {
	ID         string
	Category   string
	Kind       string
	Severity   string
	OccurredAt string
	Build      string
	Detail     string
}{
	ID:         "id",
	Category:   "category",
	Kind:       "kind",
	Severity:   "severity",
	OccurredAt: "occurred_at",
	Build:      "build",
	Detail:     "detail",
}

var OperatorEventTableColumns = struct {
	ID         string
	Category   string
	Kind       string
	Severity   string
	OccurredAt string
	Build      string
	Detail     string
}{
	ID:         "operator_event.id",
	Category:   "operator_event.category",
	Kind:       "operator_event.kind",
	Severity:   "operator_event.severity",
	OccurredAt: "operator_event.occurred_at",
	Build:      "operator_event.build",
	Detail:     "operator_event.detail",
}

// Generated where

var OperatorEventWhere = struct {
	ID         whereHelperint64
	Category   whereHelperstring
	Kind       whereHelperstring
	Severity   whereHelperstring
	OccurredAt whereHelpertime_Time
	Build      whereHelperstring
	Detail     whereHelpertypes_JSON
}{
	ID:         whereHelperint64{field: "\"operator_event\".\"id\""},
	Category:   whereHelperstring{field: "\"operator_event\".\"category\""},
	Kind:       whereHelperstring{field: "\"operator_event\".\"kind\""},
	Severity:   whereHelperstring{field: "\"operator_event\".\"severity\""},
	OccurredAt: whereHelpertime_Time{field: "\"operator_event\".\"occurred_at\""},
	Build:      whereHelperstring{field: "\"operator_event\".\"build\""},
	Detail:     whereHelpertypes_JSON{field: "\"operator_event\".\"detail\""},
}

// OperatorEventRels is where relationship names are stored.
var OperatorEventRels = struct {
}{}

// operatorEventR is where relationships are stored.
type operatorEventR struct {
}

// NewStruct creates a new relationship struct
func (*operatorEventR) NewStruct() *operatorEventR {
	return &operatorEventR{}
}

// operatorEventL is where Load methods for each relationship are stored.
type operatorEventL struct{}

var (
	operatorEventAllColumns            = []string{"id", "category", "kind", "severity", "occurred_at", "build", "detail"}
	operatorEventColumnsWithoutDefault = []string{"category", "kind", "severity", "build"}
	operatorEventColumnsWithDefault    = []string{"id", "occurred_at", "detail"}
	operatorEventPrimaryKeyColumns     = []string{"id"}
	operatorEventGeneratedColumns      = []string{"id"}
)

type (
	// OperatorEventSlice is an alias for a slice of pointers to OperatorEvent.
	// This should almost always be used instead of []OperatorEvent.
	OperatorEventSlice []*OperatorEvent

	operatorEventQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	operatorEventType                 = reflect.TypeOf(&OperatorEvent{})
	operatorEventMapping              = queries.MakeStructMapping(operatorEventType)
	operatorEventPrimaryKeyMapping, _ = queries.BindMapping(operatorEventType, operatorEventMapping, operatorEventPrimaryKeyColumns)
	operatorEventInsertCacheMut       sync.RWMutex
	operatorEventInsertCache          = make(map[string]insertCache)
	operatorEventUpdateCacheMut       sync.RWMutex
	operatorEventUpdateCache          = make(map[string]updateCache)
	operatorEventUpsertCacheMut       sync.RWMutex
	operatorEventUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single operatorEvent record from the query.
func (q operatorEventQuery) One(ctx context.Context, exec boil.ContextExecutor) (*OperatorEvent, error) {
	o := &OperatorEvent{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for operator_event")
	}

	return o, nil
}

// All returns all OperatorEvent records from the query.
func (q operatorEventQuery) All(ctx context.Context, exec boil.ContextExecutor) (OperatorEventSlice, error) {
	var o []*OperatorEvent

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to OperatorEvent slice")
	}

	return o, nil
}

// Count returns the count of all OperatorEvent records in the query.
func (q operatorEventQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count operator_event rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q operatorEventQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if operator_event exists")
	}

	return count > 0, nil
}

// OperatorEvents retrieves all the records using an executor.
func OperatorEvents(mods ...qm.QueryMod) operatorEventQuery {
	mods = append(mods, qm.From("\"operator_event\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"operator_event\".*"})
	}

	return operatorEventQuery{q}
}

// FindOperatorEvent retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindOperatorEvent(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*OperatorEvent, error) {
	operatorEventObj := &OperatorEvent{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"operator_event\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, operatorEventObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from operator_event")
	}

	return operatorEventObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *OperatorEvent) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no operator_event provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(operatorEventColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	operatorEventInsertCacheMut.RLock()
	cache, cached := operatorEventInsertCache[key]
	operatorEventInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			operatorEventAllColumns,
			operatorEventColumnsWithDefault,
			operatorEventColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, operatorEventGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(operatorEventType, operatorEventMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(operatorEventType, operatorEventMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"operator_event\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"operator_event\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into operator_event")
	}

	if !cached {
		operatorEventInsertCacheMut.Lock()
		operatorEventInsertCache[key] = cache
		operatorEventInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the OperatorEvent.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *OperatorEvent) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	operatorEventUpdateCacheMut.RLock()
	cache, cached := operatorEventUpdateCache[key]
	operatorEventUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			operatorEventAllColumns,
			operatorEventPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, operatorEventGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update operator_event, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"operator_event\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, operatorEventPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(operatorEventType, operatorEventMapping, append(wl, operatorEventPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update operator_event row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for operator_event")
	}

	if !cached {
		operatorEventUpdateCacheMut.Lock()
		operatorEventUpdateCache[key] = cache
		operatorEventUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q operatorEventQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for operator_event")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for operator_event")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o OperatorEventSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), operatorEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"operator_event\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, operatorEventPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in operatorEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all operatorEvent")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *OperatorEvent) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no operator_event provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(operatorEventColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	operatorEventUpsertCacheMut.RLock()
	cache, cached := operatorEventUpsertCache[key]
	operatorEventUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			operatorEventAllColumns,
			operatorEventColumnsWithDefault,
			operatorEventColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			operatorEventAllColumns,
			operatorEventPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert operator_event, could not build update column list")
		}

		ret := strmangle.SetComplement(operatorEventAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(operatorEventPrimaryKeyColumns))
			copy(conflict, operatorEventPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"operator_event\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(operatorEventType, operatorEventMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(operatorEventType, operatorEventMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert operator_event")
	}

	if !cached {
		operatorEventUpsertCacheMut.Lock()
		operatorEventUpsertCache[key] = cache
		operatorEventUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single OperatorEvent record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *OperatorEvent) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no OperatorEvent provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), operatorEventPrimaryKeyMapping)
	sql := "DELETE FROM \"operator_event\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from operator_event")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for operator_event")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q operatorEventQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no operatorEventQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from operator_event")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for operator_event")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o OperatorEventSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), operatorEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"operator_event\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, operatorEventPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from operatorEvent slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for operator_event")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *OperatorEvent) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindOperatorEvent(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *OperatorEventSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := OperatorEventSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), operatorEventPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"operator_event\".* FROM \"operator_event\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, operatorEventPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in OperatorEventSlice")
	}

	*o = slice

	return nil
}

// OperatorEventExists checks if the OperatorEvent row exists.
func OperatorEventExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"operator_event\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if operator_event exists")
	}

	return exists, nil
}

// Exists checks if the OperatorEvent row exists.
func (o *OperatorEvent) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return OperatorEventExists(ctx, exec, o.ID)
}
