// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// QsoHistory is an object representing the database table.
type QsoHistory struct {
	ID          int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	QsoUUID     string     `boil:"qso_uuid" json:"qso_uuid" toml:"qso_uuid" yaml:"qso_uuid"`
	Op          string     `boil:"op" json:"op" toml:"op" yaml:"op"`
	At          time.Time  `boil:"at" json:"at" toml:"at" yaml:"at"`
	Source      string     `boil:"source" json:"source" toml:"source" yaml:"source"`
	BeforeImage types.JSON `boil:"before_image" json:"before_image" toml:"before_image" yaml:"before_image"`

	R *qsoHistoryR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L qsoHistoryL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var QsoHistoryColumns = struct {
	ID          string
	QsoUUID     string
	Op          string
	At          string
	Source      string
	BeforeImage string
}{
	ID:          "id",
	QsoUUID:     "qso_uuid",
	Op:          "op",
	At:          "at",
	Source:      "source",
	BeforeImage: "before_image",
}

var QsoHistoryTableColumns = struct {
	ID          string
	QsoUUID     string
	Op          string
	At          string
	Source      string
	BeforeImage string
}{
	ID:          "qso_history.id",
	QsoUUID:     "qso_history.qso_uuid",
	Op:          "qso_history.op",
	At:          "qso_history.at",
	Source:      "qso_history.source",
	BeforeImage: "qso_history.before_image",
}

// Generated where

var QsoHistoryWhere = struct {
	ID          whereHelperint64
	QsoUUID     whereHelperstring
	Op          whereHelperstring
	At          whereHelpertime_Time
	Source      whereHelperstring
	BeforeImage whereHelpertypes_JSON
}{
	ID:          whereHelperint64{field: "\"qso_history\".\"id\""},
	QsoUUID:     whereHelperstring{field: "\"qso_history\".\"qso_uuid\""},
	Op:          whereHelperstring{field: "\"qso_history\".\"op\""},
	At:          whereHelpertime_Time{field: "\"qso_history\".\"at\""},
	Source:      whereHelperstring{field: "\"qso_history\".\"source\""},
	BeforeImage: whereHelpertypes_JSON{field: "\"qso_history\".\"before_image\""},
}

// QsoHistoryRels is where relationship names are stored.
var QsoHistoryRels = struct {
	Qso string
}{
	Qso: "Qso",
}

// qsoHistoryR is where relationships are stored.
type qsoHistoryR struct {
	Qso *Qso `boil:"Qso" json:"Qso" toml:"Qso" yaml:"Qso"`
}

// NewStruct creates a new relationship struct
func (*qsoHistoryR) NewStruct() *qsoHistoryR {
	return &qsoHistoryR{}
}

func (o *QsoHistory) GetQso() *Qso {
	if o == nil {
		return nil
	}

	return o.R.GetQso()
}

func (r *qsoHistoryR) GetQso() *Qso {
	if r == nil {
		return nil
	}

	return r.Qso
}

// qsoHistoryL is where Load methods for each relationship are stored.
type qsoHistoryL struct{}

var (
	qsoHistoryAllColumns            = []string{"id", "qso_uuid", "op", "at", "source", "before_image"}
	qsoHistoryColumnsWithoutDefault = []string{"qso_uuid", "op", "source", "before_image"}
	qsoHistoryColumnsWithDefault    = []string{"id", "at"}
	qsoHistoryPrimaryKeyColumns     = []string{"id"}
	qsoHistoryGeneratedColumns      = []string{"id"}
)

type (
	// QsoHistorySlice is an alias for a slice of pointers to QsoHistory.
	// This should almost always be used instead of []QsoHistory.
	QsoHistorySlice []*QsoHistory

	qsoHistoryQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	qsoHistoryType                 = reflect.TypeOf(&QsoHistory{})
	qsoHistoryMapping              = queries.MakeStructMapping(qsoHistoryType)
	qsoHistoryPrimaryKeyMapping, _ = queries.BindMapping(qsoHistoryType, qsoHistoryMapping, qsoHistoryPrimaryKeyColumns)
	qsoHistoryInsertCacheMut       sync.RWMutex
	qsoHistoryInsertCache          = make(map[string]insertCache)
	qsoHistoryUpdateCacheMut       sync.RWMutex
	qsoHistoryUpdateCache          = make(map[string]updateCache)
	qsoHistoryUpsertCacheMut       sync.RWMutex
	qsoHistoryUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single qsoHistory record from the query.
func (q qsoHistoryQuery) One(ctx context.Context, exec boil.ContextExecutor) (*QsoHistory, error) {
	o := &QsoHistory{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for qso_history")
	}

	return o, nil
}

// All returns all QsoHistory records from the query.
func (q qsoHistoryQuery) All(ctx context.Context, exec boil.ContextExecutor) (QsoHistorySlice, error) {
	var o []*QsoHistory

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to QsoHistory slice")
	}

	return o, nil
}

// Count returns the count of all QsoHistory records in the query.
func (q qsoHistoryQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count qso_history rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q qsoHistoryQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if qso_history exists")
	}

	return count > 0, nil
}

// Qso pointed to by the foreign key.
func (o *QsoHistory) Qso(mods ...qm.QueryMod) qsoQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"uuid\" = ?", o.QsoUUID),
	}

	queryMods = append(queryMods, mods...)

	return Qsos(queryMods...)
}

// LoadQso allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (qsoHistoryL) LoadQso(ctx context.Context, e boil.ContextExecutor, singular bool, maybeQsoHistory any, mods queries.Applicator) error {
	var slice []*QsoHistory
	var object *QsoHistory

	if singular {
		var ok bool
		object, ok = maybeQsoHistory.(*QsoHistory)
		if !ok {
			object = new(QsoHistory)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeQsoHistory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeQsoHistory))
			}
		}
	} else {
		s, ok := maybeQsoHistory.(*[]*QsoHistory)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeQsoHistory)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeQsoHistory))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &qsoHistoryR{}
		}
		args[object.QsoUUID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &qsoHistoryR{}
			}

			args[obj.QsoUUID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`qso`),
		qm.WhereIn(`qso.uuid in ?`, argsSlice...),
		qmhelper.WhereIsNull(`qso.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Qso")
	}

	var resultSlice []*Qso
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Qso")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for qso")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for qso")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Qso = foreign
		if foreign.R == nil {
			foreign.R = &qsoR{}
		}
		foreign.R.QsoHistories = append(foreign.R.QsoHistories, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.QsoUUID == foreign.UUID {
				local.R.Qso = foreign
				if foreign.R == nil {
					foreign.R = &qsoR{}
				}
				foreign.R.QsoHistories = append(foreign.R.QsoHistories, local)
				break
			}
		}
	}

	return nil
}

// SetQso of the qsoHistory to the related item.
// Sets o.R.Qso to related.
// Adds o to related.R.QsoHistories.
func (o *QsoHistory) SetQso(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Qso) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"qso_history\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, []string{"qso_uuid"}),
		strmangle.WhereClause("\"", "\"", 0, qsoHistoryPrimaryKeyColumns),
	)
	values := []any{related.UUID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.QsoUUID = related.UUID
	if o.R == nil {
		o.R = &qsoHistoryR{
			Qso: related,
		}
	} else {
		o.R.Qso = related
	}

	if related.R == nil {
		related.R = &qsoR{
			QsoHistories: QsoHistorySlice{o},
		}
	} else {
		related.R.QsoHistories = append(related.R.QsoHistories, o)
	}

	return nil
}

// QsoHistories retrieves all the records using an executor.
func QsoHistories(mods ...qm.QueryMod) qsoHistoryQuery {
	mods = append(mods, qm.From("\"qso_history\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"qso_history\".*"})
	}

	return qsoHistoryQuery{q}
}

// FindQsoHistory retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindQsoHistory(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*QsoHistory, error) {
	qsoHistoryObj := &QsoHistory{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"qso_history\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, qsoHistoryObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from qso_history")
	}

	return qsoHistoryObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *QsoHistory) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no qso_history provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(qsoHistoryColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	qsoHistoryInsertCacheMut.RLock()
	cache, cached := qsoHistoryInsertCache[key]
	qsoHistoryInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			qsoHistoryAllColumns,
			qsoHistoryColumnsWithDefault,
			qsoHistoryColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, qsoHistoryGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(qsoHistoryType, qsoHistoryMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(qsoHistoryType, qsoHistoryMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"qso_history\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"qso_history\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into qso_history")
	}

	if !cached {
		qsoHistoryInsertCacheMut.Lock()
		qsoHistoryInsertCache[key] = cache
		qsoHistoryInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the QsoHistory.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *QsoHistory) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	qsoHistoryUpdateCacheMut.RLock()
	cache, cached := qsoHistoryUpdateCache[key]
	qsoHistoryUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			qsoHistoryAllColumns,
			qsoHistoryPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, qsoHistoryGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update qso_history, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"qso_history\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, qsoHistoryPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(qsoHistoryType, qsoHistoryMapping, append(wl, qsoHistoryPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update qso_history row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for qso_history")
	}

	if !cached {
		qsoHistoryUpdateCacheMut.Lock()
		qsoHistoryUpdateCache[key] = cache
		qsoHistoryUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q qsoHistoryQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for qso_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for qso_history")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o QsoHistorySlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), qsoHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"qso_history\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, qsoHistoryPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in qsoHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all qsoHistory")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *QsoHistory) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no qso_history provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(qsoHistoryColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	qsoHistoryUpsertCacheMut.RLock()
	cache, cached := qsoHistoryUpsertCache[key]
	qsoHistoryUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			qsoHistoryAllColumns,
			qsoHistoryColumnsWithDefault,
			qsoHistoryColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			qsoHistoryAllColumns,
			qsoHistoryPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert qso_history, could not build update column list")
		}

		ret := strmangle.SetComplement(qsoHistoryAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(qsoHistoryPrimaryKeyColumns))
			copy(conflict, qsoHistoryPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"qso_history\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(qsoHistoryType, qsoHistoryMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(qsoHistoryType, qsoHistoryMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert qso_history")
	}

	if !cached {
		qsoHistoryUpsertCacheMut.Lock()
		qsoHistoryUpsertCache[key] = cache
		qsoHistoryUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single QsoHistory record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *QsoHistory) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no QsoHistory provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), qsoHistoryPrimaryKeyMapping)
	sql := "DELETE FROM \"qso_history\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from qso_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for qso_history")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q qsoHistoryQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no qsoHistoryQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from qso_history")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for qso_history")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o QsoHistorySlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), qsoHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"qso_history\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, qsoHistoryPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from qsoHistory slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for qso_history")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *QsoHistory) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindQsoHistory(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *QsoHistorySlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := QsoHistorySlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), qsoHistoryPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"qso_history\".* FROM \"qso_history\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, qsoHistoryPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in QsoHistorySlice")
	}

	*o = slice

	return nil
}

// QsoHistoryExists checks if the QsoHistory row exists.
func QsoHistoryExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"qso_history\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if qso_history exists")
	}

	return exists, nil
}

// Exists checks if the QsoHistory row exists.
func (o *QsoHistory) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return QsoHistoryExists(ctx, exec, o.ID)
}
